name: devmy_cli
description: Devmy Command Line Interfaces
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.2
  mason: any
  interact: ^2.2.0
  chalkdart: ^2.2.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.9
  lints: ^2.1.0
  test: ^1.24.0
  json_serializable: ^6.7.1

executables:
  devmy:
