name: devmy_cli
description: The Devmy CLI is a command-line interface tool that you use to initialize, develop, scaffold, and maintain Devmy applications directly from a command shell.
version: 1.6.0

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.2
  mason: any
  interact: ^2.2.0
  chalkdart: ^2.2.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.9
  lints: ^2.1.0
  test: ^1.24.0
  json_serializable: ^6.7.1

executables:
  devmy:
