name: Binaries

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
jobs:
  compile:
    if: contains(github.ref, 'refs/tags/')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        sdk: [ stable ]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: make install

      - name: Build runners
        run: make build_runner

      - name: compile
        run: make compile

      - name: Install zip
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y zip

      - name: zip
        run: zip -j "${{matrix.os}}.zip" dist/devmy

      - name: compile
        run: rm dist/devmy

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "${{matrix.os}}.zip"
