name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        sdk: [ stable ]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: make install
      - name: Build runners
        run: make build_runner
      - name: compile
        run: make compile
      - name: Install zip
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y zip
      - name: zip
        uses: montudor/action-zip@v1
        run: zip "{{matrix.os}}.zip" dist/devmy
      - name: compile
        run: rm dist/devmy
  release:
    runs-on: ubuntu-latest
    needs: [ compile ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Setup Semantic Release
        run: npm i -g semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator semantic-release-dart @semantic-release/changelog @semantic-release/git @semantic-release/github
      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release
