name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    paths:
      - doc/**
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.2
      - name: Install Vercel CLI
        working-directory: ./doc
        run: pnpm install --global vercel@latest
      - name: Pull Vercel Environment Information
        working-directory: ./doc
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Install
        working-directory: ./doc
        run: pnpm i
      - name: Build Project Artifacts
        working-directory: ./doc
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        working-directory: ./doc
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
